local_backend: true

backend:
  name: git-gateway
  repo: donroops/myPortfolioV2
  branch: main

media_folder: static/media
public_folder: /media

collections:
  - name: Project
    label: Project
    folder: cms/projects
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Full Description, widget: 'markdown' }
      - { name: url, label: Live URL }
      - { name: codeUrl, label: Code URL }
      - {
          name: tech,
          label: Tech List,
          widget: 'list',
          hint: 'Comma seperated list',
        }
      - { label: 'Vid', name: 'Vid', widget: 'file' }
      - { label: Vid Alt, name: alt, widget: string }
      - {
          label: Vid Poster,
          name: vidPoster,
          widget: image,
          required: false,
          hint: 'The picture the video initially loads with',
        }
      - {
          label: Placeholder Image,
          name: placeholder,
          widget: image,
          hint: 'Low quality blured image of first frame of vid/poster. Will show before video is loaded.',
        }
      - { label: Placeholder Image alt, name: placeholderAlt, widget: string }
